apiVersion: v1
kind: Pod
metadata:
  name: frond-end
  labels:
    project: roboshop
    environment: dev
    component: web
spec:
  containers:
  - name: web-1
    image: nginx
    ports:
    - containerPort: 80

---
# cluste-ip service is used connet the containers internall not to expose outside
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
spec:
  selector:
    project: roboshop
    environment: dev
    component: web
  ports:
  - name: http
    protocal: TCP
    port: 80
    targetPort: web-host