apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    project: roboshop
    app: frontend
    component: web
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort # By mentioning type as NodePort we can use NodePort and attached to above Pod.
  selector:
    project: roboshop
    app: frontend
    component: web
  ports:
  - name: web
    protocol: TCP
    port: 80


