apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: roman
    age: "88"
    gender: male
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    name: roman
    age: "88"
    gender: male
  ports:
  - name: web
    protocol: TCP
    containerPort: 80
  #NodePort: 8080 
