apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: web
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx
