apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    project: roboshop
    Environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      name: application
      component: catalogue
  template:
    metadata:
      labels:
        name: application
        component: catalogue      
    spec:
      containers:
      - name: catalogue
        image: nginx
