apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
      component: mongodb
  template:
    metadata:
      labels:
        tier: database
        component: mongodb
    spec:
      containers:
      - name: monogdb
        image: venkat1095/mongodb:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    tier: database
    component: mongodb
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017

