apiVersion: v1
kind: Pod
metadata:
  name: pod # Pod name
  namespace: roboshop # if not attached namespace it will attached to default name space
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80