apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec: 
  containers:
  - name: web-1
    image: nginx
    ports:
    - containerPort: 80
  - name: web-2
    image: almalinux: letest
    command: ["sleep", "100"] # it will the server for 100
    ports:
    - containerPort: 8080
