apiVersion: v1
kind: Pod
metadata: 
  name: labels
  labels:
    environmnet: dev
    project: roboshop
    component: web
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80