apiVersion: v1
kind: Pod
metadata:
  name: environment-demo
  labels:
    purpose: using environment variables
spec:
  containers:
  - name: web
    image: nginx
    env:
    - name: PROJECT_NAME
      value: "roboshop" # the values always in duble quotes i.e ("") 
    - name: COMPONENT_NAME
      value: "web" # the values always in duble quotes i.e ("") 