apiVersion: v1
kind: ConfigMap
metadata:
  name: fullconfigmap
data: 
  USER_NAME: "roboshop"
  PASSWORD: "Roboshop@123"

# for references i am using the below Pod but it should be another file.
# this for configure all Key-Value pairs in ConfigMap as container environment varibles
---
apiVersion: v1
kind: Pod
metadata:
  name: credentials

spec:
  containers:
  - name: web-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: fullconfigMap # name taken above ConfigMap  metadata name
