apiVersion: v1
kind: Secret
metadata:
  name: user-crendentials
data: 
  user_name: "cm9ib3Nob3AK" # base64 encodes i.e (roboshop) "echo "roboshop" | abse64"
  password: "Um9ib3Nob3BAMTIzCg==" # base64 encodes i.e (Roboshop@123) "echo "Ro@123boshop" | abse64"

---

apiVersion: v
kind: Pod
metadata:
  name: pulling credentials from Secret

spec:
  containers:
  - name: web-1
    image: nginx
    envFrom:
    - secretRef:
        name: user-credentials
  - name: web-2
    image: almalinux
    envFrom:
    - secretRes:
        name: user-credentials